config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'posts/index'

  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find params[:post_id]
    # comment_params.username => current_user.email
    @comment = @post.comments.create comment_params

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find params[:post_id]
    @comment = @post.comments.find params[:id]
    @comment.destroy

    redirect_to post_path @post
  end

  private def comment_params
    params.require(:comment).permit :username, :body
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About Us'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find params[:id]
  end

  def new
    @post = Post.new
  end

  def create

    @post = Post.new post_params

    @post.title = current_user.email

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end

  def edit
    @post = Post.find params[:id]
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy

    redirect_to posts_path
  end

  def update
    @post = Post.find params[:id]

    if @post.update post_params
      redirect_to @post
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<% @post.comments.each do |comment| %>
  <div class="well">
    <p><strong><%= comment.username %></strong>: <%= raw comment.body %></p>
    <% if current_user.email == 'liam@anywhich.com' or current_user.email == comment.username %>
      <%= link_to 'remove', [comment.post, comment], method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger delete-comment'%>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@post, @post.comments.build] do |form| %>
  <p class="comment-form">
    <%= form.label :body %> <br>
    <%= form.text_area :body, {:class => 'form-control'} %>
    <%= form.text_field :username, {:class => 'hidden', :value => current_user.email} %>
  </p>

  <p>
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twotter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Twotter</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Home', home_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'New Post', new_post_path %></li>
            <li class="active"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |form| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  <% end %>
  <p>
    <%= form.label :body %> <br>
    <%= form.text_area :body, {:class => 'form-control'} %>
  </p>

  <p>
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<div class="title">
  <h1>
    Twotter<%= image_tag 'logo.png', size: '50x50', alt: 'Twotter logo', class: 'logo' %>
  </h1>
</div>

<% @posts.reverse_each do |post| %>
  <div class="well post">
    <p><%= raw post.body %></p>
    <h5><strong><%= post.title %></strong></h5>
    <%= link_to 'See comments', post_path(post), :class => 'btn btn-default'%>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |form| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  <% end %>
  <p>
    <%= form.label :body %> <br>
    <%= form.text_area :body, {:class => 'form-control'} %>
  </p>

  <p>
    <%= form.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/posts/show.html.erb
<div class="post">
  <p><%= raw @post.body %></p>
  <h5><strong><%= @post.title %></strong></h5>
</div>
<% if current_user.email == 'liam@anywhich.com' or current_user.email == @post.title %>
  <%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-default' %>
  <%= link_to('Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger') %>
<% end %>

<hr>

<h3>Comments</h3>

<%= render('comments/comments') %>

<h3>New comment</h3>

<%= render('comments/form') %>